# Generated by Django 4.0.3 on 2022-03-11 06:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='year_of_birth',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1950, message='Year of birth must be before 1950'), django.core.validators.MaxValueValidator(2022, message="Year of birth can't be in the future")]),
        ),
    ]
